#pragma once

#define POINT_DEFAULT_NUMBER    0u
#define POINT_DEFAULT_POSITION  Vec2F()
#define POINT_DEFAULT_RADIUS    1.0f
#define POINT_DEFAULT_TEXT_SIZE 16u

#define CONNECTION_DEFAULT_WIDTH    0.1f
#define CONNECTION_DEFAULT_ROUNDED  0.0f

