#pragma once

#define SHIPS_SELECT_BUTTONS_NO_TEAM		0
#define SHIPS_SELECT_BUTTONS_TEAM_RED		1
#define SHIPS_SELECT_BUTTONS_TEAM_GREEN		2
#define SHIPS_SELECT_BUTTONS_TEAM_BLUE		3
#define SHIPS_SELECT_BUTTONS_TEAM_PURPURE	4