#pragma once

//#include "../Classes/GameEngine.h"

#define OPEN_GL_REALISATION_KEY_NOTHIHG     0x00
#define OPEN_GL_REALISATION_KEY_MOUSE_LEFT  0x01
#define OPEN_GL_REALISATION_KEY_UP          0x02
#define OPEN_GL_REALISATION_KEY_DOWN        0x04
#define OPEN_GL_REALISATION_KEY_FULL        0xFF

#define OPEN_GL_REALISATION_FRAMES_AFTER_CALLBAC_COUNT	3

