#pragma once

//#include "../Classes/GameEngine.h"

#define OPEN_GL_REALISATION_COMMAND_FULL	0xFFFF
#define OPEN_GL_REALISATION_COMMAND_NOTHING	0x0000

#define OPEN_GL_REALISATION_COMMAND_SELECT	0x0001
#define OPEN_GL_REALISATION_COMMAND_BACK	0x0002

#define OPEN_GL_REALISATION_BUTTON_LOST 2

#define OPEN_GL_REALISATION_FRAMES_AFTER_CALLBAC_COUNT	3

